version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:14
    branches:
      only:
        - nodejs
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: nodejs 
